"""Render an IntakeRecord as a Markdown Agent Action Audit Snapshot draft."""

from __future__ import annotations

from typing import Iterable, List

from voice_to_evidence.intake import IntakeRecord


def _bullets(items: Iterable[str], empty: str = "_(none recorded)_") -> str:
    items = list(items)
    if not items:
        return empty
    return "\n".join(f"- {item}" for item in items)


def _recommendation_block(rec: str | None) -> str:
    if not rec:
        return "**Recommendation:** _(not yet decided — human reviewer required)_"
    return f"**Recommendation (draft):** `{rec}`"


def render_snapshot(record: IntakeRecord) -> str:
    lines: List[str] = []
    lines.append(f"# Agent Action Audit Snapshot — {record.incident_id}")
    lines.append("")
    lines.append("> Draft artifact generated by voice-to-evidence.")
    lines.append("> Intended for **human safety review**, not autonomous sign-off.")
    lines.append("")

    lines.append("## Incident metadata")
    lines.append(f"- **Incident ID:** {record.incident_id}")
    lines.append(f"- **Agent:** {record.agent_name}")
    lines.append(f"- **Workflow:** {record.workflow}")
    if record.reporter:
        lines.append(f"- **Reporter:** {record.reporter}")
    if record.occurred_at:
        lines.append(f"- **Occurred at:** {record.occurred_at}")
    lines.append("")

    lines.append("## Action")
    lines.append(record.action)
    lines.append("")

    lines.append("## Permission boundary")
    lines.append(record.permission_boundary)
    lines.append("")

    lines.append("## Evidence available before action")
    lines.append(_bullets(record.evidence_before_action))
    lines.append("")

    lines.append("## Missing evidence")
    lines.append(_bullets(record.missing_evidence, empty="_(none flagged)_"))
    lines.append("")

    lines.append("## Reversibility risks")
    lines.append(_bullets(record.reversibility_risks, empty="_(none flagged)_"))
    lines.append("")

    if record.transcript:
        lines.append("## Original transcript")
        lines.append("```")
        lines.append(record.transcript.strip())
        lines.append("```")
        lines.append("")

    if record.notes:
        lines.append("## Notes")
        lines.append(record.notes.strip())
        lines.append("")

    lines.append("## Review")
    lines.append(_recommendation_block(record.recommendation))
    lines.append("")
    lines.append("---")
    lines.append(
        "_This snapshot is a draft intake artifact. It does not constitute "
        "compliance certification, legal advice, or production sign-off._"
    )
    lines.append("")
    return "\n".join(lines)
